//
//  ContentView.swift
//  App (Generated by SwiftyLaunch 2.0)
//  https://docs.swiftylaun.ch/module/app
//

import SwiftUI

struct ContentView: View {

	init() {

	}

	var body: some View {
		JokeView()
	}
}

#Preview {
	ContentView()
}
