//
//  ContentView.swift
//  App (Generated by SwiftyLaunch 2.0)
//  https://docs.swiftylaun.ch/module/app
//

import SwiftUI

struct ContentView: View {

	init() {

	}

	var body: some View {
        TabView {
            Tab("Joke", systemImage: "speaker.wave.2.bubble.fill") {
                JokeView()
            }
            Tab("Test 1", systemImage: "1.circle.fill") {
                Text("Test 1")
            }
            Tab("Test 2", systemImage: "2.circle.fill") {
                Text("Test 2")
            }
            Tab("Test 3", systemImage: "3.circle.fill") {
                Text("Test 3")
            }
        }
	}
}

#Preview {
	ContentView()
}
