//
//  ContentView.swift
//  App (Generated by SwiftyLaunch 2.0)
//  https://docs.swiftylaun.ch/module/app
//

import SwiftUI

struct ContentView: View {

	init() {

	}

	var body: some View {
		TabView {

			// Pre-made Settings View for easy native-looking settings screen.
			Tab("Settings", systemImage: "gear") {
				SettingsView()
			}

			#if DEBUG

				TabSection("DEBUG ONLY") {
					// Use this to create quick settings and toggles to streamline the development process
					Tab("Developer", systemImage: "hammer") {
						DeveloperSettingsView()
					}
				}

			#endif
		}
	}
}

#Preview {
	ContentView()
}
